// Copyright (C) 2026 Industrial Algebra
// SPDX-License-Identifier: Apache-2.0

//! Behavioral tests for Cargo.lock resolution — Phase 19-C slice 4. The
//! inspector parses the workspace `Cargo.lock` (read-only) and records the
//! *resolved* versions of packages — complementing the declared version
//! requirements captured from `Cargo.toml`.

use std::path::{Path, PathBuf};

use karpal_discovery::inspect::inspect_workspace;

const ROOT_TOML: &str = "\
[workspace]
members = [\"fixture-crate\"]
resolver = \"2\"
";

const CRATE_TOML: &str = "\
[package]
name = \"fixture-crate\"
version = \"0.1.0\"
edition = \"2021\"
";

const LOCKFILE: &str = "\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"serde\"
version = \"1.0.210\"
source = \"registry+https://github.com/rust-lang/crates.io-index\"
checksum = \"deadbeef\"

[[package]]
name = \"fixture-crate\"
version = \"0.1.0\"

[[package]]
name = \"lonis-schema\"
version = \"0.0.1\"
source = \"git+https://github.com/Industrial-Algebra/Lonis.git#4aa23a6\"
";

fn lock_fixture() -> tempfile::TempDir {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("Cargo.toml"), ROOT_TOML).unwrap();
    let crate_dir = dir.path().join("fixture-crate");
    std::fs::create_dir_all(crate_dir.join("src")).unwrap();
    std::fs::write(crate_dir.join("Cargo.toml"), CRATE_TOML).unwrap();
    std::fs::write(crate_dir.join("src/lib.rs"), "").unwrap();
    std::fs::write(dir.path().join("Cargo.lock"), LOCKFILE).unwrap();
    dir
}

#[test]
fn lockfile_is_captured_when_present() {
    let dir = lock_fixture();
    let snapshot = inspect_workspace(dir.path());
    let lock = snapshot.lock.as_ref().expect("lockfile snapshot present");
    assert_eq!(lock.version, 4);
}

#[test]
fn lockfile_is_absent_when_missing() {
    // A workspace with no Cargo.lock → `lock` is None.
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("Cargo.toml"), ROOT_TOML).unwrap();
    let crate_dir = dir.path().join("fixture-crate");
    std::fs::create_dir_all(crate_dir.join("src")).unwrap();
    std::fs::write(crate_dir.join("Cargo.toml"), CRATE_TOML).unwrap();
    std::fs::write(crate_dir.join("src/lib.rs"), "").unwrap();
    let snapshot = inspect_workspace(dir.path());
    assert!(snapshot.lock.is_none());
}

#[test]
fn registry_dep_resolves_to_a_version_and_source() {
    let dir = lock_fixture();
    let snapshot = inspect_workspace(dir.path());
    let lock = snapshot.lock.as_ref().unwrap();
    let serde = lock.packages.get("serde").expect("serde resolved");
    assert_eq!(serde.version, "1.0.210");
    assert!(
        serde
            .source
            .as_ref()
            .is_some_and(|s| s.contains("registry")),
        "serde source should be the registry: {:?}",
        serde.source
    );
}

#[test]
fn workspace_member_has_no_source() {
    let dir = lock_fixture();
    let snapshot = inspect_workspace(dir.path());
    let lock = snapshot.lock.as_ref().unwrap();
    // fixture-crate is a path/workspace member → no `source` in the lockfile.
    let member = lock.packages.get("fixture-crate").expect("member resolved");
    assert_eq!(member.version, "0.1.0");
    assert!(member.source.is_none());
}

#[test]
fn git_dep_resolves_to_a_git_source() {
    let dir = lock_fixture();
    let snapshot = inspect_workspace(dir.path());
    let lock = snapshot.lock.as_ref().unwrap();
    let lonis = lock
        .packages
        .get("lonis-schema")
        .expect("lonis-schema resolved");
    assert_eq!(lonis.version, "0.0.1");
    assert!(
        lonis
            .source
            .as_ref()
            .is_some_and(|s| s.contains("git") && s.contains("Lonis")),
        "lonis-schema source should be git: {:?}",
        lonis.source
    );
}

// -- real-workspace assertion --

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .canonicalize()
        .expect("workspace root resolves")
}

#[test]
fn karpal_lockfile_resolves_workspace_members_and_registry_deps() {
    let snapshot = inspect_workspace(&workspace_root());
    let lock = snapshot.lock.as_ref().expect("Karpal has a Cargo.lock");
    // karpal-core is a workspace member → resolved to its declared version,
    // no source.
    let core = lock
        .packages
        .get("karpal-core")
        .expect("karpal-core resolved");
    assert_eq!(core.version, "0.8.0");
    assert!(core.source.is_none());
    // A registry dep for contrast.
    let serde = lock.packages.get("serde").expect("serde resolved");
    assert!(
        serde
            .source
            .as_ref()
            .is_some_and(|s| s.contains("registry"))
    );
}
